using System;
using System.Collections.Generic;
using UnityEngine;

namespace ClickerGame.EconomyAnalysis
{
    public enum EconomyBuild { Base, Custom, MaxSkillTree }

    [Serializable]
    public sealed class SkillPurchase
    {
        public SkillNodeSO node;
        [Min(0)] public int level;
    }

    // One entry per occupied cell. Rolls are explicit and never regenerated by A/B tests.
    [Serializable]
    public sealed class EconomyTile
    {
        public Vector2Int cell;
        public TileModifierSO tile;
        public List<StatModifier> rolledModifiers = new();
    }

    [Serializable]
    public sealed class EconomyRoundAssumption
    {
        [Min(1)] public int fromRound = 1;
        public EconomyBuild build;
        [Tooltip("0: use the selected build's RoundDuration, clamped to 30–90 seconds.")]
        public float durationOverride;
        [Min(1)] public int effectiveTargets = 4;
        public List<SkillPurchase> purchases = new();
        public List<StatModifier> extraGlobalModifiers = new();
        public List<EconomyTile> tiles = new();
    }

    [CreateAssetMenu(menuName = "Analysis/Economy Balance Profile")]
    public sealed class EconomyBalanceProfileSO : ScriptableObject
    {
        public PlanterSO planter;
        public CoreStatsSO coreStats;
        public PlantHealthScalingSO healthScaling;
        public ProgressionSO currentXpCurve;
        public ResonanceRulesSO resonanceRules;
        public List<SkillNodeSO> skillTree = new();
        [Tooltip("0: read actual prefab spawnPoints; empty spawnPoints uses occupied cells, as PlanterBrain does.")]
        [Min(0)] public int spawnerCountOverride;
        public bool enableResonance = true;
        [Min(1)] public int seed = 12345;
        [Range(1, 1000)] public int trials = 100;
        [Range(10, 240)] public int simulationFps = 60;
        [Min(0)] public double goldWeight = 1;
        [Min(0)] public double ironWeight = 7;
        [Min(0)] public double stoneWeight = 14;
        [Range(1, 130)] public int checkpoint = 129;
        public List<int> checkpoints = new() { 1, 5, 10, 20, 40, 65, 80, 100, 120, 130 };
        [Tooltip("Explicit piecewise history. Each row is held until the next row; no automatic progression or purchases. First row must be round 1.")]
        public List<EconomyRoundAssumption> history = new() { new EconomyRoundAssumption() };
    }
}
